# Medium Tests: Run on all commits/PRs to dev branch

language: c
dist: trusty

git:
  depth: 1

branches:
  only:
  - dev
  - master
  - travisTest
  - travisCiTest
  
addons:
  apt:
    update: true
    packages:
      - lcov
script:
  find ./ name "gcno"
env:
  global:
    - FUZZERTEST=-T2mn
      ZSTREAM_TESTTIME=-T2mn
      DECODECORPUS_TESTTIME=-T1mn
    - CODECOV_TOKEN=:39285ee5-9536-44ee-8d9c-2f1a46e851e5
    - coverage=yes
    - CFLAGS=" -fPIC -shared -lgcov -ftest-coverage -fprofile-arcs "

before_install:
  - pip install --user codecov

matrix:
  fast_finish: true
  include:
    - name: Trusty (Test All)
      script:
        - make  test

    - name: gcc-6 + gcc-7 compilation
      script:
        - make gcc6install gcc7install 
        - CC=gcc-6   CFLAGS+=-Werror  make -j all
        - make clean
        - CC=gcc-7  CFLAGS+=-Werror  make -j all

      after_failure:
        - cat "$TRAVIS_BUILD_DIR"/builddir/meson-logs/testlog.txt
      after_success: 
        # Creating report
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --capture --output-file coverage.info # capture coverage info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
        - lcov --list coverage.info #debug info
        - codecov -t 39285ee5-9536-44ee-8d9c-2f1a46e851e5

  allow_failures:
    - env: ALLOW_FAILURES=true
    
