# Medium Tests: Run on all commits/PRs to dev branch

language: c
dist: trusty
before_install:
  - pip install --user codecov
git:
  depth: 1

branches:
  only:
  - dev
  - master
  - travisTest
  - travisCiTest

addons:
  apt:
    update: true

env:
  global:
    - FUZZERTEST=-T2mn
      ZSTREAM_TESTTIME=-T2mn
      DECODECORPUS_TESTTIME=-T1mn
    - CODECOV_TOKEN=:39285ee5-9536-44ee-8d9c-2f1a46e851e5

matrix:
  fast_finish: true
  include:
    - name: Trusty (Versions Compatibility Test)
      script:
        - make -C tests versionsTest
        
      after_failure:
        - cat "$TRAVIS_BUILD_DIR"/builddir/meson-logs/testlog.txt
      after_success:
        - codecov -t 39285ee5-9536-44ee-8d9c-2f1a46e851e5
  allow_failures:
    - env: ALLOW_FAILURES=true
